# Generated by Django 4.1.7 on 2023-04-16 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnotherModel',
            fields=[
                ('Circuit', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('SET_Block', models.TextField(db_column='SET Block', max_length=255)),
                ('memo', models.CharField(blank=True, max_length=100, null=True)),
                ('memodate', models.CharField(blank=True, max_length=100, null=True)),
                ('checked', models.IntegerField(blank=True, default=0, null=True)),
                ('reverse', models.IntegerField(blank=True, default=0, null=True)),
                ('list_node', models.CharField(blank=True, max_length=100, null=True)),
                ('list_BlockPATH', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MyMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('ship', models.CharField(max_length=255)),
                ('nodes', models.TextField()),
                ('edges', models.TextField()),
                ('nodepos', models.TextField()),
            ],
        ),
    ]
